CREATE TABLE QUIZFORM
(
    ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
    QUESTION         VARCHAR(255) NOT NULL,
    ANSWERA          VARCHAR(255) NOT NULL,
    ANSWERB          VARCHAR(255) NOT NULL,
    ANSWERC          VARCHAR(255) NOT NULL,
    ANSWERD          VARCHAR(255) NOT NULL,
    CORRECTANSWER    VARCHAR(255) NOT NULL,
    TIMEPERQUESTION BIGINT       NOT NULL

);